FROM jenkins/jenkins:lts-jdk21

# 설치용 계정
USER root

# 설치 후 .deb 패키지 캐시 및 apt 인덱스 삭제
RUN apt-get update && \
    apt-get install -y git curl unzip openjdk-21-jdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV GRADLE_VERSION=8.14.3
ENV GRADLE_HOME=/opt/gradle/gradle-${GRADLE_VERSION}
ENV PATH=${GRADLE_HOME}/bin:${PATH}

RUN mkdir -p /opt/gradle && \
    curl -fsSL https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -o gradle.zip && \
    unzip gradle.zip -d /opt/gradle && \
    rm gradle.zip

RUN chown -R jenkins:jenkins /opt/gradle

# 젠킨스 계정으로 변경
USER jenkins

EXPOSE 8080
EXPOSE 50000
