spring:
  application:
    name: my-portal-news-batch
  batch:
    jdbc:
      initialize-schema: always  # 메타 데이터 테이블 자동으로 만들어지게 설정
      schema: classpath:org/springframework/batch/core/schema-postgresql.sql

#  datasource:
#    meta:
#      driver-class-name: org.postgresql.Driver
#      jdbc-url:
#      username:
#      password:
#    main:
#      driver-class-name: org.postgresql.Driver
#      jdbc-url:
#      username:
#      password:
